### ISSUE TITLE
How to Visualize Robots

### ISSUE THREAD

**Issue by kaipengfang** [nicklashansen/puppeteer#1]
Hello, your work is very interesting~ I should have successfully reproduced an inference, but I'm more curious about how to visualize the results. Like the images in your paper and on your website? Thank you very much!
![image](https://github.com/nicklashansen/puppeteer/assets/68734187/75bf9cc8-bd0a-4f13-a4a8-952b914e7f02)

**Comment by nicklashansen** [comment]
Thank you for your interest! Videos should be saved by default. Have you searched your logs for any *.mp4 files?

**Comment by AmingWu** [comment]
@fangkaipeng Do you perform the visualization successfully?

**Comment by plyfager** [comment]
I managed to perform the visualization. However, I didn't really get the meaning of the video. (find in puppeteer/logs/corridor/1/default/videos/corridor-0.mp4)

https://github.com/nicklashansen/puppeteer/assets/22982797/44e0b71c-e0e8-4f58-a9be-565e9105b258

**Comment by nicklashansen** [comment]
Looks like it renders one of the egocentric camera here rather than the third-person camera used in our videos. Let me look into this and get back to you soon!

**Comment by maxjkwang** [comment]
Hi Nicklas,

Have you had a chance to look into this issue? I can also render the videos, but all of them are from the egocentric view instead of the third-person view (as on the website), regardless of the task.

Thanks!

**Comment by nicklashansen** [comment]
Yes! I was able to locate the problem and will issue a fix later today :-)

**Comment by nicklashansen** [comment]
Commit https://github.com/nicklashansen/puppeteer/commit/c588d5299c2eb2952a84bccf5a8c4e2724d36c82 fixes the rendering + pins the versioning for all dependencies since numpy 2.0 seems to be incompatible with some of the other packages that we depend on. Thanks for your patience! Let me know if you run into any other issues.

**Comment by nicklashansen** [comment]
Closing this issue, but feel free to reopen if you have any follow-up questions!
